### ISSUE TITLE
use_getip = True 出现的问题

### ISSUE THREAD

**Issue by 13271473920** [honmashironeko/ProxyCat#14]
用use_getip时候检测re正则需要把^删除
当获取IP数量为1时   到代理地址更换时间就不会动了

**Comment by 13271473920** [comment]
如果用IP格式为 IP:PORT的时候  IP检测是过不去的

**Comment by honmashironeko** [comment]
> 如果用IP格式为 IP:PORT的时候  IP检测是过不去的

当然过不去，你都没指定协议，请完整阅读 readme 关于使用方法部分

**Comment by honmashironeko** [comment]
> 用use_getip时候检测re正则需要把^删除
> 当获取IP数量为1时   到代理地址更换时间就不会动了
> 

错误的，这是功能预设，到时间后需要在中间件收到新的请求才会获取新的，这个目的是防止长期使用时 被过度消耗 ip 资源

**Comment by honmashironeko** [comment]
感谢您的反馈和对本项目的支持，不过目前这两个问题并不是 bug 哈
