### ISSUE TITLE
use_getip = True 格式问题

### ISSUE THREAD

**Issue by edwordl1** [honmashironeko/ProxyCat#16]
![image](https://github.com/user-attachments/assets/ce9f7af7-9ad4-4592-9561-37602a68bcf4)
按照下面这种格式会提示上述错误
![image](https://github.com/user-attachments/assets/27c1eafb-2329-4057-8587-46859badacad)

**Comment by honmashironeko** [comment]
从首页重新下载 zip，不要从发行版里下，后面要更新 1.9，会连带其他 bug 一起修复
