### ISSUE TITLE
计时器结束后无任何响应

### ISSUE THREAD

**Issue by ghost** [honmashironeko/ProxyCat#20]
<img width="786" alt="image" src="https://github.com/user-attachments/assets/b7c3d5d3-710f-412a-bff9-7b00e32e47e7">

问题如图所示
我的环境 Python 3.11.2 系统 debian12

**Comment by honmashironeko** [comment]
此处为功能设计，倒计时结束需要收到新的请求才会更换，目的是减少 ip 资源消耗
