### ISSUE TITLE
socks5 问题

### ISSUE THREAD

**Issue by NewBieLD** [honmashironeko/ProxyCat#8]
socks5 格式是不是有问题，单独使用代理ip 是正常的，使用脚本转换后，访问提示400

**Comment by honmashironeko** [comment]
有发现这个问题，但是测试的时候发现其实是代理地址不支持协议，你可以换成 http，目前有几家的代理是相反的，用 http 会无效，socks 正常，有些又是 socks 无效，http 正常

**Comment by honmashironeko** [comment]
后续会考虑增强适配性，尽量兼容更多的请求协议

**Comment by honmashironeko** [comment]
已更新，增加更多适配，请再测试
